---
- hosts: all
  become: yes
  tasks:
  - name: Installation of apache
    apt:
      name: apache2
      state: present
      update_cache: yes
    notify:
    - Restart apache2
  - name: Installing php
    apt:
      name: {{ 'items' }}
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
    notify:
    - Restart apache2
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      enabled: yes
      state: restarted