---
- hosts: all
  become: yes
  tasks:
  - name: Display Ip and hostname of machines
    debug:
      msg: Date and time{{ansible_date_time.date}} is IP Address is {{ansible_default_ipv4.address}} and {{ansible_all_ipv4_addresses[0]}}
