---
- hosts: all
  become: yes
  tasks:
  - name: Display Ip and hostname of machines
    debug:
      msg: hostname is {{ansible_nodename}} and IP is {{ansible_all_ipv4_addresses}} and also {{ansible_default_ipv4}}
      