---
- hosts: all
  become: yes
  tasks:
  - name: Updating packages & Installation of apache
    apt: 
      name: apache2
      state: present
      update_cache: yes
  - name: Apache2 service restart
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: Php Installation
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
  - name: Apache2 service restart
    service:
      name: apache2
      enabled: yes
      state: restarted  
   