---
- hosts: all
  become: yes
  vars:
    - myname: template examples
  tasks:
  - name: create a file with static content
    copy:
      src: hello.txt
      dest: /home/ansible/hello
  - name: create a file with dynamic content
    templates:
      src: message.j2
      dest: /home/ansible/message