---
- hosts: all
  become: yes
  tasks:
  - name: Creation of testgroup user
    group:
      name: testgroup
      state: present
  - name: creation of test users
    user:
      name: "{{item}}"
      groups: testgroup
    with_items:
      - test1
      - test2
      - test3
